"use client";
import { useState } from "react";
import { Utensils, X } from "lucide-react";
import { getCopy } from "@/locales";
import type { Language } from "@/types/app";
export type FoodNowOptions = { budget: number | null; radius: number; localOnly: boolean; openNow: boolean; lateOnly: boolean };
export function FoodNowSheet({ language, defaultRadius, onClose, onSubmit }: { language: Language; defaultRadius: number; onClose: () => void; onSubmit: (value: FoodNowOptions) => void }) {
  const copy = getCopy(language); const [budget, setBudget] = useState<number | null>(200); const [radius, setRadius] = useState(Math.min(defaultRadius, 2000)); const [localOnly, setLocalOnly] = useState(false); const [openNow, setOpenNow] = useState(true); const [lateOnly, setLateOnly] = useState(false);
  return <div className="fixed inset-0 z-[130] flex items-end justify-center bg-black/65 backdrop-blur-sm"><button type="button" onClick={onClose} aria-label={copy.close} className="absolute inset-0" /><section role="dialog" aria-modal="true" className="amd-glass-strong relative w-full max-w-[520px] rounded-t-[30px] p-4 pb-[calc(18px+env(safe-area-inset-bottom))]"><div className="mx-auto mb-4 h-1.5 w-12 rounded-full bg-white/15" /><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Utensils className="h-5 w-5 text-[#00D9FF]" /><h3 className="text-[20px] font-bold">{copy.foodNow}</h3></div><button type="button" onClick={onClose} className="amd-btn grid h-11 w-11 place-items-center rounded-full"><X className="h-4 w-4" /></button></div><p className="mt-4 text-[11px] font-semibold text-[var(--amd-text-2)]">{copy.budget}</p><div className="mt-2 grid grid-cols-4 gap-2">{[100,200,300,null].map((value) => <button key={String(value)} type="button" onClick={() => setBudget(value)} className={`amd-chip min-h-11 px-2 text-[10px] ${budget === value ? "amd-chip-active" : ""}`}>{value == null ? copy.unlimited : `≤ ${value}`}</button>)}</div><p className="mt-4 text-[11px] font-semibold text-[var(--amd-text-2)]">{copy.distance}</p><div className="mt-2 grid grid-cols-3 gap-2">{[[500,"500 ม."],[1000,"1 กม."],[2000,"2 กม."]] .map(([value,label]) => <button key={String(value)} type="button" onClick={() => setRadius(Number(value))} className={`amd-chip min-h-11 text-[10px] ${radius === value ? "amd-chip-active" : ""}`}>{label}</button>)}</div><div className="mt-4 grid grid-cols-3 gap-2"><button type="button" aria-pressed={localOnly} onClick={() => setLocalOnly(!localOnly)} className={`amd-chip min-h-11 px-2 text-[9px] ${localOnly ? "amd-chip-active" : ""}`}>{copy.localOnly}</button><button type="button" aria-pressed={openNow} onClick={() => setOpenNow(!openNow)} className={`amd-chip min-h-11 px-2 text-[9px] ${openNow ? "amd-chip-active" : ""}`}>{copy.openNow}</button><button type="button" aria-pressed={lateOnly} onClick={() => setLateOnly(!lateOnly)} className={`amd-chip min-h-11 px-2 text-[9px] ${lateOnly ? "amd-chip-active" : ""}`}>{copy.late}</button></div><button type="button" onClick={() => onSubmit({ budget, radius, localOnly, openNow, lateOnly })} className="amd-btn amd-btn-primary mt-5 h-12 w-full rounded-2xl font-bold">{copy.chooseFood}</button></section></div>;
}
