"use client";
import { useState } from "react";
import { Crosshair, Home, MapPin, X } from "lucide-react";
import { getCopy } from "@/locales";
import type { CustomHomeLocation, Language } from "@/types/app";
export function HomeLocationSheet({ language, custom, onDorm, onCurrent, onCustom, onClose }: { language: Language; custom: CustomHomeLocation | null; onDorm: () => void; onCurrent: () => void; onCustom: (value: CustomHomeLocation) => void; onClose: () => void }) {
  const copy = getCopy(language);
  const [name, setName] = useState(custom?.name || "");
  const [lat, setLat] = useState(custom?.latitude?.toString() || "");
  const [lng, setLng] = useState(custom?.longitude?.toString() || "");
  const valid = Number.isFinite(Number(lat)) && Number.isFinite(Number(lng)) && Math.abs(Number(lat)) <= 90 && Math.abs(Number(lng)) <= 180 && name.trim().length > 0;
  return <div className="fixed inset-0 z-[130] flex items-end justify-center bg-black/65 backdrop-blur-sm"><button type="button" onClick={onClose} aria-label={copy.close} className="absolute inset-0" /><section role="dialog" aria-modal="true" className="amd-glass-strong relative w-full max-w-[520px] rounded-t-[30px] p-4 pb-[calc(18px+env(safe-area-inset-bottom))]"><div className="mx-auto mb-4 h-1.5 w-12 rounded-full bg-white/15" /><div className="flex items-center justify-between"><h3 className="text-[20px] font-bold">{copy.homeLocation}</h3><button type="button" onClick={onClose} className="amd-btn grid h-11 w-11 place-items-center rounded-full"><X className="h-4 w-4" /></button></div><div className="mt-4 grid gap-2"><button type="button" onClick={onDorm} className="amd-glass flex min-h-12 items-center gap-3 rounded-2xl px-4 text-left"><Home className="h-5 w-5 text-[#00D9FF]" /><span className="font-semibold">{copy.dorm}</span></button><button type="button" onClick={onCurrent} className="amd-glass flex min-h-12 items-center gap-3 rounded-2xl px-4 text-left"><Crosshair className="h-5 w-5 text-[#00D9FF]" /><span className="font-semibold">{copy.useCurrentLocation}</span></button></div><div className="mt-4 rounded-2xl border border-[rgba(120,160,210,.14)] p-3"><div className="mb-3 flex items-center gap-2"><MapPin className="h-4 w-4 text-[#9B6CFF]" /><p className="text-[13px] font-semibold">{copy.customLocation}</p></div><input value={name} onChange={(e) => setName(e.target.value)} placeholder={copy.locationName} className="amd-input h-11 w-full px-3 text-[12px] outline-none" /><div className="mt-2 grid grid-cols-2 gap-2"><input inputMode="decimal" value={lat} onChange={(e) => setLat(e.target.value)} placeholder={copy.latitude} className="amd-input h-11 w-full px-3 text-[12px] outline-none" /><input inputMode="decimal" value={lng} onChange={(e) => setLng(e.target.value)} placeholder={copy.longitude} className="amd-input h-11 w-full px-3 text-[12px] outline-none" /></div><button type="button" disabled={!valid} onClick={() => valid && onCustom({ name: name.trim(), latitude: Number(lat), longitude: Number(lng) })} className="amd-btn amd-btn-primary mt-3 h-11 w-full rounded-xl disabled:opacity-40">{copy.save}</button></div></section></div>;
}
