"use client";
import { useRef, useState } from "react";
import { ChevronUp, Navigation, ShieldCheck, Star } from "lucide-react";
import { CATEGORY_MAP } from "@/data/categories";
import { getCopy } from "@/locales";
import { formatDistance, formatPrice, getPlaceOpenStatus, googleMapsDirectionsUrl } from "@/lib/place-utils";
import type { Language } from "@/types/app";
import type { Place } from "@/types/place";
type SheetSize = "collapsed" | "half" | "expanded";
export function MapBottomSheet({ place, language, onDetails }: { place: Place; language: Language; onDetails: () => void }) {
  const copy = getCopy(language); const [size, setSize] = useState<SheetSize>("half"); const startY = useRef<number | null>(null); const status = getPlaceOpenStatus(place); const category = CATEGORY_MAP[place.category];
  function endDrag(y: number) { if (startY.current == null) return; const delta = y - startY.current; startY.current = null; if (delta > 55) setSize(size === "expanded" ? "half" : "collapsed"); if (delta < -55) setSize(size === "collapsed" ? "half" : "expanded"); }
  const heightClass = size === "collapsed" ? "max-h-[126px]" : size === "half" ? "max-h-[290px]" : "max-h-[68dvh] overflow-y-auto";
  return <section className={`amd-glass-strong absolute bottom-3 left-3 right-3 z-30 rounded-[24px] p-3.5 transition-[max-height] duration-200 ${heightClass}`}><button type="button" aria-label="Resize place sheet" onPointerDown={(e) => { startY.current = e.clientY; e.currentTarget.setPointerCapture?.(e.pointerId); }} onPointerUp={(e) => endDrag(e.clientY)} className="mx-auto mb-2 block h-6 w-20 touch-none"><span className="mx-auto block h-1.5 w-12 rounded-full bg-white/18" /></button><div className="flex gap-3">{place.coverImage || place.image ? <img src={place.coverImage || place.image || ""} alt="" loading="lazy" decoding="async" className="h-[104px] w-[104px] shrink-0 rounded-[16px] object-cover" /> : <div className="grid h-[104px] w-[104px] shrink-0 place-items-center rounded-[16px] bg-white/[0.04] text-4xl">{category?.icon || "📍"}</div>}<div className="min-w-0 flex-1"><div className="flex items-start gap-2"><h3 className="min-w-0 flex-1 truncate text-[17px] font-bold">{place.name}</h3>{place.verified && <span className="flex items-center gap-1 rounded-md border border-[rgba(0,229,195,.25)] px-2 py-1 text-[8px] font-bold text-[#00E5C3]"><ShieldCheck className="h-3 w-3" /> VERIFIED</span>}</div><p className="mt-1 text-[10px] text-[var(--amd-text-2)]">{category?.name} • {place.area}</p><p className="mt-2 text-[11px]"><span className={status.isOpen ? "text-[#00E5C3]" : "text-[var(--amd-text-3)]"}>{status.label}</span>{status.secondaryText ? ` • ${status.secondaryText}` : ""}</p><p className="mt-1 text-[10px] text-[var(--amd-text-2)]">{formatPrice(place)} • {formatDistance(place.distanceKm)}{place.rating != null ? ` • ★ ${place.rating.toFixed(1)}${place.reviewCount != null ? ` (${place.reviewCount})` : ""}` : ""}</p><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={onDetails} className="amd-btn h-11 rounded-xl border border-[rgba(120,160,210,.22)] text-[10px] font-semibold">{copy.details}</button><a href={googleMapsDirectionsUrl(place)} target="_blank" rel="noreferrer" className="amd-btn amd-btn-primary flex h-11 items-center justify-center gap-1.5 rounded-xl text-[10px] font-bold"><Navigation className="h-4 w-4" />{copy.navigate}</a></div></div></div>{size === "expanded" && <div className="mt-3 border-t border-[rgba(120,160,210,.12)] pt-3 text-[11px] leading-5 text-[var(--amd-text-2)]"><p>{place.shortDescription}</p><div className="mt-2 flex flex-wrap gap-1.5">{place.tags.slice(0,6).map((tag) => <span key={tag} className="rounded-lg bg-white/[0.05] px-2 py-1 text-[9px]">{tag}</span>)}</div></div>}{size === "collapsed" && <ChevronUp className="pointer-events-none absolute right-4 top-3 h-4 w-4 text-[var(--amd-text-3)]" />}</section>;
}
