from pathlib import Path

path = Path('lib/google-cloud-enrichment.ts')
text = path.read_text()

text = text.replace(
'''import type { GoogleDiscoveryCandidate, GoogleLiveDetails } from "@/lib/google-live";''',
'''import type { GoogleAccessibility, GoogleDiscoveryCandidate, GoogleLiveDetails, GoogleParkingOptions, GooglePaymentOptions } from "@/lib/google-live";'''
)

old_type = '''export type GoogleCloudPlacePayload = {\n  address: string | null;\n  latitude: number | null;\n  longitude: number | null;\n  rating: number | null;\n  reviewCount: number | null;\n  openNow: boolean | null;\n  openingHoursText: string[];\n  phone: string | null;\n  website: string | null;\n  googleMapsUrl: string | null;\n  priceLevel: string | null;\n  businessStatus: string | null;\n  fetchedAt: string;\n};'''
new_type = '''export type GoogleCloudPlacePayload = {\n  address: string | null;\n  shortAddress: string | null;\n  latitude: number | null;\n  longitude: number | null;\n  rating: number | null;\n  reviewCount: number | null;\n  openNow: boolean | null;\n  openingHoursText: string[];\n  phone: string | null;\n  internationalPhone: string | null;\n  website: string | null;\n  googleMapsUrl: string | null;\n  priceLevel: string | null;\n  businessStatus: string | null;\n  types: string[];\n  primaryType: string | null;\n  hasDelivery: boolean | null;\n  hasDineIn: boolean | null;\n  hasTakeout: boolean | null;\n  isReservable: boolean | null;\n  hasCurbsidePickup: boolean | null;\n  accessibility: GoogleAccessibility;\n  parkingOptions: GoogleParkingOptions;\n  paymentOptions: GooglePaymentOptions;\n  fetchedAt: string;\n};'''
if old_type not in text:
    raise SystemExit('payload type target not found')
text = text.replace(old_type, new_type, 1)

old_safe = '''  return {\n    address: typeof record.address === "string" ? record.address : null,\n    latitude: typeof record.latitude === "number" ? record.latitude : null,\n    longitude: typeof record.longitude === "number" ? record.longitude : null,\n    rating: typeof record.rating === "number" ? record.rating : null,\n    reviewCount: typeof record.reviewCount === "number" ? record.reviewCount : null,\n    openNow: typeof record.openNow === "boolean" ? record.openNow : null,\n    openingHoursText: Array.isArray(record.openingHoursText) ? record.openingHoursText.map(String) : [],\n    phone: typeof record.phone === "string" ? record.phone : null,\n    website: typeof record.website === "string" ? record.website : null,\n    googleMapsUrl: typeof record.googleMapsUrl === "string" ? record.googleMapsUrl : null,\n    priceLevel: typeof record.priceLevel === "string" ? record.priceLevel : null,\n    businessStatus: typeof record.businessStatus === "string" ? record.businessStatus : null,\n    fetchedAt: record.fetchedAt,\n  };'''
new_safe = '''  const bool = (value: unknown) => typeof value === "boolean" ? value : null;\n  const accessibility = (record.accessibility || {}) as Partial<GoogleAccessibility>;\n  const parking = (record.parkingOptions || {}) as Partial<GoogleParkingOptions>;\n  const payment = (record.paymentOptions || {}) as Partial<GooglePaymentOptions>;\n  return {\n    address: typeof record.address === "string" ? record.address : null,\n    shortAddress: typeof record.shortAddress === "string" ? record.shortAddress : null,\n    latitude: typeof record.latitude === "number" ? record.latitude : null,\n    longitude: typeof record.longitude === "number" ? record.longitude : null,\n    rating: typeof record.rating === "number" ? record.rating : null,\n    reviewCount: typeof record.reviewCount === "number" ? record.reviewCount : null,\n    openNow: bool(record.openNow),\n    openingHoursText: Array.isArray(record.openingHoursText) ? record.openingHoursText.map(String) : [],\n    phone: typeof record.phone === "string" ? record.phone : null,\n    internationalPhone: typeof record.internationalPhone === "string" ? record.internationalPhone : null,\n    website: typeof record.website === "string" ? record.website : null,\n    googleMapsUrl: typeof record.googleMapsUrl === "string" ? record.googleMapsUrl : null,\n    priceLevel: typeof record.priceLevel === "string" ? record.priceLevel : null,\n    businessStatus: typeof record.businessStatus === "string" ? record.businessStatus : null,\n    types: Array.isArray(record.types) ? record.types.map(String) : [],\n    primaryType: typeof record.primaryType === "string" ? record.primaryType : null,\n    hasDelivery: bool(record.hasDelivery),\n    hasDineIn: bool(record.hasDineIn),\n    hasTakeout: bool(record.hasTakeout),\n    isReservable: bool(record.isReservable),\n    hasCurbsidePickup: bool(record.hasCurbsidePickup),\n    accessibility: {\n      wheelchairAccessibleEntrance: bool(accessibility.wheelchairAccessibleEntrance),\n      wheelchairAccessibleParking: bool(accessibility.wheelchairAccessibleParking),\n      wheelchairAccessibleRestroom: bool(accessibility.wheelchairAccessibleRestroom),\n      wheelchairAccessibleSeating: bool(accessibility.wheelchairAccessibleSeating),\n    },\n    parkingOptions: {\n      freeParkingLot: bool(parking.freeParkingLot),\n      paidParkingLot: bool(parking.paidParkingLot),\n      freeStreetParking: bool(parking.freeStreetParking),\n      paidStreetParking: bool(parking.paidStreetParking),\n      freeGarageParking: bool(parking.freeGarageParking),\n      paidGarageParking: bool(parking.paidGarageParking),\n      valetParking: bool(parking.valetParking),\n    },\n    paymentOptions: {\n      cashOnly: bool(payment.cashOnly),\n      creditCards: bool(payment.creditCards),\n      debitCards: bool(payment.debitCards),\n      nfc: bool(payment.nfc),\n    },\n    fetchedAt: record.fetchedAt,\n  };'''
if old_safe not in text:
    raise SystemExit('safe payload target not found')
text = text.replace(old_safe, new_safe, 1)

old_sanitize = '''  return {\n    address: live.address,\n    latitude: live.latitude,\n    longitude: live.longitude,\n    rating: live.rating,\n    reviewCount: live.reviewCount,\n    openNow: live.openNow,\n    openingHoursText: live.openingHoursText,\n    phone: live.phone,\n    website: live.website,\n    googleMapsUrl: live.googleMapsUrl,\n    priceLevel: live.priceLevel,\n    businessStatus: live.businessStatus,\n    fetchedAt: live.fetchedAt,\n  };'''
new_sanitize = '''  return {\n    address: live.address,\n    shortAddress: live.shortAddress ?? null,\n    latitude: live.latitude,\n    longitude: live.longitude,\n    rating: live.rating,\n    reviewCount: live.reviewCount,\n    openNow: live.openNow,\n    openingHoursText: live.openingHoursText,\n    phone: live.phone,\n    internationalPhone: live.internationalPhone ?? null,\n    website: live.website,\n    googleMapsUrl: live.googleMapsUrl,\n    priceLevel: live.priceLevel,\n    businessStatus: live.businessStatus,\n    types: live.types ?? [],\n    primaryType: live.primaryType ?? null,\n    hasDelivery: live.hasDelivery ?? null,\n    hasDineIn: live.hasDineIn ?? null,\n    hasTakeout: live.hasTakeout ?? null,\n    isReservable: live.isReservable ?? null,\n    hasCurbsidePickup: live.hasCurbsidePickup ?? null,\n    accessibility: live.accessibility ?? { wheelchairAccessibleEntrance: null, wheelchairAccessibleParking: null, wheelchairAccessibleRestroom: null, wheelchairAccessibleSeating: null },\n    parkingOptions: live.parkingOptions ?? { freeParkingLot: null, paidParkingLot: null, freeStreetParking: null, paidStreetParking: null, freeGarageParking: null, paidGarageParking: null, valetParking: null },\n    paymentOptions: live.paymentOptions ?? { cashOnly: null, creditCards: null, debitCards: null, nfc: null },\n    fetchedAt: live.fetchedAt,\n  };'''
if old_sanitize not in text:
    raise SystemExit('sanitize target not found')
text = text.replace(old_sanitize, new_sanitize, 1)

insert_after = '''  if (next.priceLevel == null) {\n    const priceLevel = normalizedPriceLevel(payload.priceLevel);\n    if (priceLevel != null) { next.priceLevel = priceLevel; mark("priceLevel"); }\n  }\n'''
rich_merge = '''  if (next.delivery == null && payload.hasDelivery != null) { next.delivery = payload.hasDelivery; mark("delivery"); }\n  if (next.dineIn == null && payload.hasDineIn != null) { next.dineIn = payload.hasDineIn; mark("dineIn"); }\n  if (next.takeaway == null && payload.hasTakeout != null) { next.takeaway = payload.hasTakeout; mark("takeaway"); }\n  if (next.wheelchairAccessible == null && payload.accessibility.wheelchairAccessibleEntrance != null) { next.wheelchairAccessible = payload.accessibility.wheelchairAccessibleEntrance; mark("wheelchairAccessible"); }\n\n  if (!next.paymentMethods.length) {\n    const methods = [\n      payload.paymentOptions.creditCards ? "credit_card" : null,\n      payload.paymentOptions.debitCards ? "debit_card" : null,\n      payload.paymentOptions.nfc ? "nfc" : null,\n      payload.paymentOptions.cashOnly ? "cash_only" : null,\n    ].filter((value): value is string => Boolean(value));\n    if (methods.length) { next.paymentMethods = methods; mark("paymentMethods"); }\n  }\n\n  if (next.parking.available == null) {\n    const parkingValues = Object.values(payload.parkingOptions);\n    if (parkingValues.some((value) => value === true)) {\n      next.parking = { ...next.parking, available: true };\n      mark("parking.available");\n    }\n  }\n\n  next.googleDetails = {\n    shortAddress: payload.shortAddress,\n    internationalPhone: payload.internationalPhone,\n    types: payload.types,\n    primaryType: payload.primaryType,\n    businessStatus: payload.businessStatus,\n    reservable: payload.isReservable,\n    curbsidePickup: payload.hasCurbsidePickup,\n    accessibility: payload.accessibility,\n    parkingOptions: payload.parkingOptions,\n    paymentOptions: payload.paymentOptions,\n    lastUpdatedAt: payload.fetchedAt,\n  };\n  mark("googleDetails");\n'''
if insert_after not in text:
    raise SystemExit('rich merge anchor not found')
text = text.replace(insert_after, insert_after + rich_merge, 1)

# Add the same non-destructive field supplements to review candidates without linking identity.
review_anchor = '''  if (next.priceLevel == null) {\n    const priceLevel = normalizedPriceLevel(payload.priceLevel);\n    if (priceLevel != null) { next.priceLevel = priceLevel; mark("priceLevel"); }\n  }\n  if (next.latitude != null && next.longitude != null && next.distanceKm == null) {'''
review_repl = '''  if (next.priceLevel == null) {\n    const priceLevel = normalizedPriceLevel(payload.priceLevel);\n    if (priceLevel != null) { next.priceLevel = priceLevel; mark("priceLevel"); }\n  }\n  if (next.delivery == null && payload.hasDelivery != null) { next.delivery = payload.hasDelivery; mark("delivery"); }\n  if (next.dineIn == null && payload.hasDineIn != null) { next.dineIn = payload.hasDineIn; mark("dineIn"); }\n  if (next.takeaway == null && payload.hasTakeout != null) { next.takeaway = payload.hasTakeout; mark("takeaway"); }\n  if (next.wheelchairAccessible == null && payload.accessibility.wheelchairAccessibleEntrance != null) { next.wheelchairAccessible = payload.accessibility.wheelchairAccessibleEntrance; mark("wheelchairAccessible"); }\n  next.googleDetails = {\n    shortAddress: payload.shortAddress, internationalPhone: payload.internationalPhone, types: payload.types, primaryType: payload.primaryType,\n    businessStatus: payload.businessStatus, reservable: payload.isReservable, curbsidePickup: payload.hasCurbsidePickup,\n    accessibility: payload.accessibility, parkingOptions: payload.parkingOptions, paymentOptions: payload.paymentOptions, lastUpdatedAt: payload.fetchedAt,\n  };\n  if (next.latitude != null && next.longitude != null && next.distanceKm == null) {'''
if review_anchor not in text:
    raise SystemExit('review merge anchor not found')
text = text.replace(review_anchor, review_repl, 1)

old_candidate = '''  const payload: GoogleCloudPlacePayload = {\n    address: candidate.address,\n    latitude: candidate.latitude,\n    longitude: candidate.longitude,\n    rating: candidate.rating,\n    reviewCount: candidate.reviewCount,\n    openNow: candidate.openNow,\n    openingHoursText: [],\n    phone: null,\n    website: null,\n    googleMapsUrl: candidate.googleMapsUrl,\n    priceLevel: null,\n    businessStatus: null,\n    fetchedAt,\n  };'''
new_candidate = '''  const payload: GoogleCloudPlacePayload = {\n    address: candidate.address,\n    shortAddress: null,\n    latitude: candidate.latitude,\n    longitude: candidate.longitude,\n    rating: candidate.rating,\n    reviewCount: candidate.reviewCount,\n    openNow: candidate.openNow,\n    openingHoursText: [],\n    phone: null,\n    internationalPhone: null,\n    website: null,\n    googleMapsUrl: candidate.googleMapsUrl,\n    priceLevel: null,\n    businessStatus: null,\n    types: candidate.primaryType ? [candidate.primaryType] : [],\n    primaryType: candidate.primaryType,\n    hasDelivery: null,\n    hasDineIn: null,\n    hasTakeout: null,\n    isReservable: null,\n    hasCurbsidePickup: null,\n    accessibility: { wheelchairAccessibleEntrance: null, wheelchairAccessibleParking: null, wheelchairAccessibleRestroom: null, wheelchairAccessibleSeating: null },\n    parkingOptions: { freeParkingLot: null, paidParkingLot: null, freeStreetParking: null, paidStreetParking: null, freeGarageParking: null, paidGarageParking: null, valetParking: null },\n    paymentOptions: { cashOnly: null, creditCards: null, debitCards: null, nfc: null },\n    fetchedAt,\n  };'''
if old_candidate not in text:
    raise SystemExit('candidate payload target not found')
text = text.replace(old_candidate, new_candidate, 1)

path.write_text(text)
